; PlatformIO Project Configuration File
; Project: C4 Airsoft - Firmware PIS (Spec-Driven Development)
; Microcontroller: ESP32 DevKit v1 (30-pin)
; Reference: constitution.md, plan.md, C4A-ICD-001

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Configuração de monitor serial
monitor_speed = 115200
upload_speed = 921600

; Flags de compilação
build_flags = 
    -I include
    -D CORE_DEBUG_LEVEL=0
    -std=gnu++17

; Dependências de bibliotecas externas homologadas
lib_deps =
    chris--a/Keypad @ ^3.1.1
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    fastled/FastLED @ ^3.6.0
